name: Repro cachix-related devenv bug

on:
  workflow_dispatch:

jobs:
  populate-enfoldsystems-cachix-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    strategy:
      matrix:
        devenv-ver: [ 1.6.1, 1.7, 1.8.1 ]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - name: Install devenv
        run: |
          nix profile install --accept-flake-config \
            github:cachix/devenv/v${{ matrix.devenv-ver }}
      - name: Run devenv shell
        run: |
          log=output.log
          search="Binary cache enfoldsystems doesn\'t exist"
          devenv shell -- true 2>&1 | tee $log
          if grep -q  $log"; then
            echo "Error: '$search' found in $log
            exit 1
          fi
