name: Repro cachix-related devenv bug

on:
  workflow_dispatch:

jobs:
  populate-enfoldsystems-cachix-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    strategy:
      matrix:
        devenv-ver: [ 1.7, 1.8, 1.8.1 ]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - run: ./bootstrap --unattended --devenv-version=${{ matrix.devenv-ver }}
      - name: Populate cachix cache
        run: |
          df -h
          echo $CACHIX_AUTH_TOKEN | base64
          devenv shell -- true
          df -h
