name: Repro cachix-related devenv bug

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    strategy:
      fail-fast: false
      matrix:
        devenv-ver: [ 1.8.1 ]
        nix-installer: [ "determinate", "cachix-31.5.2" , "cachix-26" ]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
        if: matrix.nix-installer == 'determinate'
      - uses: cachix/install-nix-action@v26
        if: matrix.nix-installer == 'cachix-26'
      - uses: cachix/install-nix-action@v31.5.2
        if: matrix.nix-installer == 'cachix-31.5.2'
      - name: Install devenv
        run: |
          nix profile install --accept-flake-config \
            github:cachix/devenv/v${{ matrix.devenv-ver }}
      - name: Run devenv shell
        run: |
          set -x
          log=output.log
          devenv shell -- true 2>&1 | tee $log
          ls -al output.log
          search=(
            "Binary cache enfoldsystems doesn"
            "does not appear to be a binary cache"
          )
          for string in "${search[@]}"; do
            if grep -q "$string" "$log"; then
              echo "Error: "$search" found in "$log""
              exit 1
            fi
          done
